### ISSUE TITLE
What is the role of cadQuery here?

### ISSUE THREAD

**Issue by ceremcem** [jmwright/cadquery-gui#19]
Hi, 

This might be a premature question, as I didn't read the source code deeply (just briefly took a look). I'm confused about something: What is the role of cadQuery here? As far as I could understand, electron creates a Gui, Three.js visualizes the 3D object and provides some controls; so what does cadQuery do? Does it re-calculate the model, send the resulting object (like, STL or something that Three.js understands) over zerorpc and let Three.js update the model?

**Comment by ceremcem** [comment]
I mean, [like this?](https://github.com/ceremcem/node-occ-sample/)

**Comment by jmwright** [comment]
@ceremcem Sorry, I missed your first post on this somehow. CadQuery is being used to execute the script and returns a JSON representation that three.js is then being used to display. There's no decoupling between the execution and display, the child process just returns the JSON directly and that's passed into the viewer.

https://github.com/jmwright/cadquery-gui/blob/master/assets/js/builder.js#L31

**Comment by jmwright** [comment]
Another thing to note is that this project is set up to rely on an external editor or IDE for CadQuery script development. There was originally an editor built in, but that's been taken out to allow people to use an editor of their choice. There are so many great editors out there already, that it didn't make sense to try to compete with a custom one.

CQ-Editor is a newer CadQuery IDE, and uses the Spyder editor. So it's at least using a more mainstream editor from a larger project.

https://github.com/CadQuery/CQ-editor

**Comment by ceremcem** [comment]
NP, sometimes we miss the notifications. 

I wasn't aware of CQ-Editor, it seems promising. I just wanted to walk completely with cadQuery, ie. without using FreeCAD at all (at the time of posting the first comment) so I was looking for a visual window for that.

Anyhow, as far as I could understand, general idea is 
1. Create the model using OCC API
2. Send the model to OCC Kernel
3. Produce the 3D model in a format that display unit understands (JSON or BREP, or glTF, which fits the bill) (JSON in this case though)
4. Send the model to the display unit (Three.js in this case)

I'm on my way to build a joined CAD application (https://github.com/ceremcem/aecad) for both electric/electronic circuit generation and 3D design. I'll use [ScadaJS](https://github.com/aktos-io/scada.js) for that purpose which already solves #8 here. I think there are some code we could share. 

I want to cooperate if you don't mind.
